"""add faculty field

Revision ID: 04715cd8ea07
Revises: a6a30ec05ab7
Create Date: 2020-11-05 11:11:06.655777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04715cd8ea07'
down_revision = 'a6a30ec05ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_group', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'groups', ['has_group'], ['id'])
    op.drop_column('users', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'groups', ['group'], ['id'])
    op.drop_column('users', 'has_group')
    # ### end Alembic commands ###
