"""group

Revision ID: 41280bb76567
Revises: 4b84ebf27673
Create Date: 2020-11-04 17:46:54.503661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41280bb76567'
down_revision = '4b84ebf27673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('users', sa.Column('group', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'groups', ['group'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'group')
    op.drop_table('groups')
    # ### end Alembic commands ###
