"""events

Revision ID: 62a8fa6a8ff4
Revises: cfe889c09c51
Create Date: 2020-11-21 04:18:12.726033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a8fa6a8ff4'
down_revision = 'cfe889c09c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
