"""Event

Revision ID: a3ead2a4123e
Revises: cf8ca8c9e66a
Create Date: 2020-11-18 17:50:37.488854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ead2a4123e'
down_revision = 'a3ead2a4123e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('day', sa.String(), nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'faculty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('faculty', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'events', 'faculties', ['faculty'], ['id'])
    op.drop_column('events', 'day')
    # ### end Alembic commands ###
