"""add faculty field

Revision ID: a6a30ec05ab7
Revises: e9b270459154
Create Date: 2020-11-05 11:10:15.701965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a30ec05ab7'
down_revision = 'e9b270459154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
