"""add faculty field

Revision ID: e4b8491598e7
Revises: ebe634ab3711
Create Date: 2020-11-05 10:51:48.220242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b8491598e7'
down_revision = 'ebe634ab3711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
