"""add faculty field

Revision ID: e9b270459154
Revises: e4b8491598e7
Create Date: 2020-11-05 11:05:44.678724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b270459154'
down_revision = 'e4b8491598e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('is_supreme', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'is_supreme')
    # ### end Alembic commands ###
